---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/en/community
  label: Community
  create: all
  match: "**/*"
- type: directory
  path: content/en/case-studies
  label: Case studies
  create: all
  match: "**/*"
- type: directory
  path: content/en/docs
  label: Docs
  create: all
  match: "**/*"
- type: directory
  path: content/en/includes
  label: Includes
  create: all
  match: "**/*"
- type: directory
  path: content/en/examples
  label: Examples
  create: all
  match: "**/*"
- type: directory
  path: content/en/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/en/partners
  label: Partners
  create: all
  match: "**/*"
- type: directory
  path: content/en
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
